# Generated by Django 5.2.1 on 2025-05-22 16:08

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemfeature",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="systemimage",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="systemmodule",
            options={
                "ordering": ["-created"],
                "verbose_name": "System Module",
                "verbose_name_plural": "System Modules",
            },
        ),
        migrations.AlterModelOptions(
            name="systemtype",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name_plural": "system types",
            },
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={
                "ordering": ["category", "name"],
                "verbose_name_plural": "technologies",
            },
        ),
        migrations.RemoveField(
            model_name="systemmodule",
            name="content",
        ),
        migrations.RemoveField(
            model_name="systemmodule",
            name="outcome",
        ),
        migrations.RemoveField(
            model_name="systemmodule",
            name="related_projects",
        ),
        migrations.RemoveField(
            model_name="systemmodule",
            name="solutions",
        ),
        migrations.AddField(
            model_name="systemfeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("core", "Core Feature"),
                    ("advanced", "Advanced Feature"),
                    ("integration", "Integration"),
                    ("performance", "Performance"),
                    ("security", "Security"),
                    ("ui", "User Interface"),
                ],
                default="core",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemfeature",
            name="implementation_status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("tested", "Tested"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemimage",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="Alt text for accessibility", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("screenshot", "Screenshot"),
                    ("diagram", "Diagram"),
                    ("workflow", "Workflow"),
                    ("ui", "User Interface"),
                    ("architecture", "Architecture"),
                    ("demo", "Demo"),
                    ("other", "Other"),
                ],
                default="screenshot",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="architecture_diagram",
            field=models.ImageField(
                blank=True,
                help_text="System architecture diagram",
                null=True,
                upload_to="systems/diagrams/",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="deployment_date",
            field=models.DateField(
                blank=True, help_text="Production deployment date", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="description",
            field=markdownx.models.MarkdownxField(
                default="system description",
                help_text="Main system description and overview",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="documentation_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="features_overview",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Key features and capabilities"
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="future_enhancements",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Planned improvement and roadmap"
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="performance_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Performance score (0.0-100.0)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Normal"), (3, "High"), (4, "Critical")],
                default=2,
                help_text="Development priority",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="related_systems",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other systems that integrate with this one",
                to="projects.systemmodule",
                verbose_name="Related Systems",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="technical_details",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Technical implementation details"
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="uptime_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="System uptime percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemtype",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technology",
            name="category",
            field=models.CharField(
                choices=[
                    ("language", "Programming Language"),
                    ("framework", "Framework/Library"),
                    ("database", "Database"),
                    ("cloud", "Cloud Service"),
                    ("tool", "Development Tool"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="systemimage",
            name="image",
            field=models.ImageField(upload_to="systems/gallery/"),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="System header banner (1200x400px recommended)",
                null=True,
                upload_to="systems/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="challenges",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Development challenges and solutions"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="completion_percent",
            field=models.IntegerField(
                default=100, help_text="Development completion percentage (0-100)"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="complexity",
            field=models.IntegerField(
                choices=[
                    (1, "Basic"),
                    (2, "Intermediate"),
                    (3, "Advanced"),
                    (4, "Complex"),
                    (5, "Enterprise"),
                ],
                default=2,
                help_text="System Complexity level",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="demo_url",
            field=models.URLField(blank=True, help_text="Interactive demo URL"),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Development completion date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Brief summary for display on system cards"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Feature this system on the homepage"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for homepage (800x600px recommended)",
                null=True,
                upload_to="systems/featured/",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="live_url",
            field=models.URLField(blank=True, help_text="Live demo/deployment URL"),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Development start date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_development", "In Development"),
                    ("testing", "Testing Phase"),
                    ("deployed", "Deployed"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="system_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated system identifier (e.g. SYS-001)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="System card thumbnail (400x300px recommended)",
                null=True,
                upload_to="systems/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="code",
            field=models.CharField(
                help_text="Short code for display in hexagon (e.g., ML, WEB, API, DATA)",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="color",
            field=models.CharField(
                default="#00f0ff",
                help_text="Hex color code for HUD accent (e.g., #00f0ff)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="color",
            field=models.CharField(
                default="#00f0ff",
                help_text="Hex color code for HUD display(e.g., #00f0ff)",
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metric_unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (%, ms, MB, etc)",
                        max_length=20,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performace"),
                            ("usage", "Usage"),
                            ("uptime", "Uptime"),
                            ("response_time", "Response Time"),
                            ("throughput", "Throughput"),
                            ("error_rate", "Error Rate"),
                            ("custom", "Custom"),
                        ],
                        default="performance",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is current/latest metric value",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="projects.systemmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
