# Generated by Django 5.2.1 on 2025-06-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_systemfeature_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemmetric",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="systemmodule",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "System Module",
                "verbose_name_plural": "System Modules",
            },
        ),
        migrations.RenameField(
            model_name="systemmetric",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="systemmodule",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="systemmodule",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
