# Generated by Django 5.2.1 on 2025-06-13 18:57

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_systemmodule_actual_dev_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemmodule",
            name="related_systems",
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="challenges",
            field=markdownx.models.MarkdownxField(
                blank=True,
                help_text="Development challenges faced and how they were overcome",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="completion_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Completion percentage (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="description",
            field=markdownx.models.MarkdownxField(
                help_text="Full project description in Markdown"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="features_overview",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Key features and capabilities overview"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="future_enhancements",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Planned improvement and next steps"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="performance_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Performance score (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
