# Generated by Django 5.2.1 on 2025-07-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_systemmodule_learning_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("html_url", models.URLField()),
                ("clone_url", models.URLField()),
                ("homepage", models.URLField(blank=True, null=True)),
                ("stars_count", models.IntegerField(default=0)),
                ("forks_count", models.IntegerField(default=0)),
                ("watchers_count", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("is_fork", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("github_created_at", models.DateTimeField()),
                ("github_updated_at", models.DateTimeField()),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "related_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_repositories",
                        to="projects.systemmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
                "ordering": ["-github_updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("bytes_count", models.BigIntegerField()),
                ("percentage", models.FloatField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="projects.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-bytes_count"],
                "unique_together": {("repository", "language")},
            },
        ),
    ]
