# Generated by Django 5.2.1 on 2025-07-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_githubrepository_githublanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="avg_commits_per_month",
            field=models.FloatField(default=0.0, help_text="Average commits per month"),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="commit_sync_page",
            field=models.IntegerField(
                default=1, help_text="Last synced page for pagination"
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="commits_last_30_days",
            field=models.IntegerField(default=0, help_text="Commits in last 30 days"),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="commits_last_synced",
            field=models.DateTimeField(
                blank=True, help_text="When commit data was last synced", null=True
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="commits_last_year",
            field=models.IntegerField(default=0, help_text="Commits in last year"),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="last_commit_date",
            field=models.DateTimeField(
                blank=True, help_text="Date of most recent commit", null=True
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="last_commit_message",
            field=models.TextField(
                blank=True, help_text="Message of the most recent commit"
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="last_commit_sha",
            field=models.CharField(
                blank=True, help_text="SHA of most recent commit", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="total_commits",
            field=models.IntegerField(
                default=0, help_text="Total commits in repository"
            ),
        ),
    ]
