# Generated by Django 5.2.1 on 2025-07-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_githubrepository_avg_commits_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="commit_weeks_last_synced",
            field=models.DateTimeField(
                blank=True, help_text="When weekly commit data last synced", null=True
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="enable_detailed_tracking",
            field=models.BooleanField(
                default=False,
                help_text="Enable weekly commit tracking (auto-enabled for system-linked repos)",
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="stats_etag",
            field=models.CharField(
                blank=True,
                help_text="ETag for GitHub stats API conditional requests",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="GitHubCommitWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="ISO year (YYYY)")),
                ("week", models.IntegerField(help_text="ISO week number (1-53)")),
                (
                    "month",
                    models.IntegerField(
                        help_text="Month Number (1-2) of week start date"
                    ),
                ),
                (
                    "month_name",
                    models.CharField(
                        help_text="Month Name (e.g. January)", max_length=10
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(help_text="Quarter (1-4) for reporting"),
                ),
                ("week_start_date", models.DateField(help_text="Monday of this week")),
                ("week_end_date", models.DateField(help_text="Sunday of this week")),
                (
                    "commit_count",
                    models.IntegerField(default=0, help_text="Commits in this week"),
                ),
                ("lines_added", models.IntegerField(blank=True, default=0)),
                ("lines_deleted", models.IntegerField(blank=True, default=0)),
                ("files_changed", models.IntegerField(blank=True, default=0)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "github_etag",
                    models.CharField(
                        blank=True,
                        help_text="ETag for conditional requests",
                        max_length=64,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_weeks",
                        to="projects.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-week"],
                "indexes": [
                    models.Index(
                        fields=["repository", "year", "week"],
                        name="projects_gi_reposit_d74f15_idx",
                    ),
                    models.Index(
                        fields=["repository", "year", "month"],
                        name="projects_gi_reposit_76d528_idx",
                    ),
                    models.Index(
                        fields=["repository", "quarter", "year"],
                        name="projects_gi_reposit_324c6d_idx",
                    ),
                    models.Index(
                        fields=["week_start_date"],
                        name="projects_gi_week_st_e0e22c_idx",
                    ),
                    models.Index(
                        fields=["month", "year"], name="projects_gi_month_459407_idx"
                    ),
                ],
                "unique_together": {("repository", "year", "week")},
            },
        ),
    ]
