# Generated by Django 5.2.1 on 2025-07-24 17:11

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_githubrepository_commit_weeks_last_synced_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmodule",
            name="features_overview",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Key features and usage examples"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="technical_details",
            field=markdownx.models.MarkdownxField(
                blank=True,
                help_text="Technical implementation details and setup instructions",
            ),
        ),
        migrations.CreateModel(
            name="ArchitectureComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Streamlit Frontend)",
                        max_length=100,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend Interface"),
                            ("backend", "Backend Service"),
                            ("api", "External API"),
                            ("database", "Data Storage"),
                            ("processing", "Data Processing"),
                            ("file_io", "File Input/Output"),
                            ("authentication", "Authentication"),
                            ("deployment", "Deployment/Hosting"),
                            ("other", "Other Component"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "position_x",
                    models.FloatField(
                        default=0.0, help_text="X coordinates in 3D space"
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        default=0.0, help_text="Y coordinates in 3D space"
                    ),
                ),
                (
                    "position_z",
                    models.FloatField(
                        default=0.0, help_text="Z coordinates in 3D space"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#00ffff",
                        help_text="Hex color for component visualization",
                        max_length=7,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=15, help_text="Visual size (10-30 recommended)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Technical description for tooltips/hover info",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_core",
                    models.BooleanField(
                        default=False, help_text="Mark as core/central component"
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="architecture_components",
                        to="projects.systemmodule",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary technology used in this component",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.technology",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "unique_together": {("system", "name")},
            },
        ),
        migrations.CreateModel(
            name="ArchitectureConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("data_flow", "Data Flow"),
                            ("api_call", "API Request/Response"),
                            ("dependency", "Dependency"),
                            ("file_transfer", "File Transfer"),
                            ("authentication", "Authentication"),
                            ("deployment", "Deployment Pipeline"),
                            ("user_interaction", "User Interaction"),
                        ],
                        default="data_flow",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label for connection line (e.g., 'Geocoding Request')",
                        max_length=50,
                    ),
                ),
                (
                    "line_color",
                    models.CharField(
                        default="#00ffff",
                        help_text="Color for connection line",
                        max_length=7,
                    ),
                ),
                (
                    "line_width",
                    models.PositiveIntegerField(
                        default=2, help_text="Line thickness (1-5 recommended)"
                    ),
                ),
                (
                    "is_bidirectional",
                    models.BooleanField(default=False, help_text="Two-way connection"),
                ),
                (
                    "from_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="projects.architecturecomponent",
                    ),
                ),
                (
                    "to_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="projects.architecturecomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_component", "to_component")},
            },
        ),
    ]
