# Generated by Django 5.2.1 on 2025-07-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_technology_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="category",
            field=models.CharField(
                choices=[
                    ("language", "Programming Language"),
                    ("framework", "Framework/Library"),
                    ("database", "Database"),
                    ("cloud", "Cloud Service"),
                    ("tool", "Development Tool"),
                    ("os", "Operating Systems & Distros"),
                    ("ai", "AI & Machine Learning"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
