# Generated by Django 5.2.1 on 2025-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_technology_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemskillgain",
            name="technologies_used",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which technologies were used to apply this skill in this project?",
                related_name="skill_applications",
                to="projects.technology",
            ),
        ),
    ]
