# Generated by Django 5.2.1 on 2025-10-03 19:01

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_systemskillgain_technologies_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemmodule",
            name="features_overview",
        ),
        migrations.RemoveField(
            model_name="systemmodule",
            name="technical_details",
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="setup_instructions",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Setup instructions and implementation details"
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="usage_examples",
            field=markdownx.models.MarkdownxField(
                blank=True, help_text="Usage examples and key features"
            ),
        ),
    ]
