# Generated by Django 5.2.1 on 2025-10-29 13:06

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_remove_systemmodule_features_overview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmodule",
            name="challenges",
            field=markdownx.models.MarkdownxField(
                blank=True,
                help_text="Development challenge this system solved, and solution/approach",
            ),
        ),
    ]
