# Generated by Django 5.2.1 on 2025-10-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_alter_systemmodule_challenges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemskillgain",
            name="skill_level_after",
        ),
        migrations.RemoveField(
            model_name="systemskillgain",
            name="skill_level_before",
        ),
    ]
