# Generated by Django 5.2.1 on 2025-10-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_remove_systemskillgain_skill_level_after_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningmilestone",
            name="confidence_boost",
        ),
        migrations.RemoveField(
            model_name="learningmilestone",
            name="difficulty_level",
        ),
    ]
