# Generated by Django 5.2.1 on 2025-10-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_remove_learningmilestone_confidence_boost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemmodule",
            name="architecture_diagram",
        ),
        migrations.RemoveField(
            model_name="systemmodule",
            name="future_enhancements",
        ),
    ]
