# Generated by Django 5.2.1 on 2025-05-21 22:54

import datetime
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", markdownx.models.MarkdownxField()),
                (
                    "meta_description",
                    models.CharField(help_text="SEO meta description", max_length=160),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("handle", models.CharField(blank=True, max_length=100)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon name (e.g., 'fa-github')",
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.RemoveField(
            model_name="focusarea",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="specialty",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="education",
            name="profile",
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-end_date", "-start_date"],
                "verbose_name_plural": "Education",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-end_date", "-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["category", "display_order"]},
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="current",
            new_name="is_current",
        ),
        migrations.RemoveField(
            model_name="education",
            name="year_end",
        ),
        migrations.RemoveField(
            model_name="education",
            name="year_start",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="year_end",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="year_start",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="years",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(default="world-domination", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(default=datetime.date(2025, 5, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_date",
            field=models.DateField(default=datetime.date(2025, 5, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="technologies",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of technologies used",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="color",
            field=models.CharField(
                default="#00f0ff", help_text="Hex color code", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon name (e.g., fa-python)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="position",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("languages", "Programming Languages"),
                    ("frameworks", "Frameworks & Libraries"),
                    ("tools", "Tools & Technologies"),
                    ("databases", "Databases"),
                    ("other", "Other Skills"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                help_text="Skill level from 1-5",
            ),
        ),
        migrations.DeleteModel(
            name="ContactMethod",
        ),
        migrations.DeleteModel(
            name="FocusArea",
        ),
        migrations.DeleteModel(
            name="Specialty",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
