# Generated by Django 5.2.1 on 2025-06-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contact_corepage_sociallink_remove_focusarea_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corepage",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="corepage",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
