# Generated by Django 5.2.1 on 2025-06-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_created_corepage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="slug",
            field=models.SlugField(default="zoom", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="slug",
            field=models.SlugField(default="aaaa", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="slug",
            field=models.SlugField(default="awefawe", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="corepage",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
