# Generated by Django 5.2.1 on 2025-06-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_options_alter_systemlogentry_options_and_more"),
        ("core", "0004_education_slug_experience_slug_skill_slug_and_more"),
        ("projects", "0003_alter_systemmetric_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="inquiry_category",
            field=models.CharField(
                choices=[
                    ("project", "Project Inquiry"),
                    ("hiring", "Job/Hiring"),
                    ("collaboration", "Collaboration"),
                    ("question", "General Question"),
                    ("feedback", "Feedback"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Visitor IP address", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low Priority"),
                    ("normal", "Normal Priority"),
                    ("high", "High Priority"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="referrer_page",
            field=models.CharField(
                blank=True, help_text="Page the visitor came from", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="response_date",
            field=models.DateTimeField(
                blank=True, help_text="When response was sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="response_sent",
            field=models.BooleanField(
                default=False, help_text="Has response been sent"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="user_agent",
            field=models.TextField(blank=True, help_text="Browser/device info"),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_certified",
            field=models.BooleanField(
                default=False, help_text="Have certification in this skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_currently_learning",
            field=models.BooleanField(
                default=False, help_text="Currently improving this skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Display prominently on homepage"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="last_used",
            field=models.DateField(
                blank=True, help_text="When skill last used professionally", null=True
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="related_technology",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to corresponding technology in projects app",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_profile",
                to="projects.technology",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="years_experience",
            field=models.FloatField(
                default=0.0, help_text="Years of experience with this skill"
            ),
        ),
        migrations.CreateModel(
            name="PortfolioAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("page_views", models.IntegerField(default=0)),
                (
                    "bounce_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of single-page sessions"
                    ),
                ),
                (
                    "avg_session_duration",
                    models.IntegerField(
                        default=0, help_text="Average session duration in seconds"
                    ),
                ),
                ("datalog_views", models.IntegerField(default=0)),
                ("system_views", models.IntegerField(default=0)),
                ("contact_form_submissions", models.IntegerField(default=0)),
                ("github_clicks", models.IntegerField(default=0)),
                ("top_country", models.CharField(blank=True, max_length=50)),
                ("top_city", models.CharField(blank=True, max_length=50)),
                ("top_referrer", models.CharField(blank=True, max_length=200)),
                ("organic_search_percentage", models.FloatField(default=0.0)),
                (
                    "top_datalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_days_as_top",
                        to="blog.post",
                    ),
                ),
                (
                    "top_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_days_as_top",
                        to="projects.systemmodule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Portfolio Analytics",
                "ordering": ["-date"],
            },
        ),
    ]
