# Generated by Django 5.2.1 on 2025-06-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contact_inquiry_category_contact_ip_address_and_more"),
        ("projects", "0006_systemmodule_learning_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="career_relevance",
            field=models.IntegerField(
                choices=[
                    (1, "1 stars"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=4,
                help_text="Relevance to software development career (1-5 stars)",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="certification_url",
            field=models.URLField(
                blank=True, help_text="Link to certificate or completion proof"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="hours_completed",
            field=models.IntegerField(
                default=0, help_text="Total hours of instruction/study"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="learning_intensity",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                ],
                default=3,
                help_text="Learning intensity/difficulty (1=Easy, 5=Very Intense)",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="learning_type",
            field=models.CharField(
                choices=[
                    ("formal_degree", "Formal Degree"),
                    ("online_course", "Online Course"),
                    ("certification", "Certification"),
                    ("bootcamp", "Bootcamp"),
                    ("self_study", "Self-Study"),
                    ("workshop", "Workshop"),
                ],
                default="formal_degree",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="platform",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'edX HarvardX', 'Udemy', 'University of Alabama'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="related_systems",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects/Systems that applied knowledge from this education",
                related_name="education_background",
                to="projects.systemmodule",
            ),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="datalog_entries_written",
            field=models.IntegerField(
                default=0, help_text="Learning documentation entries created"
            ),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="job_board_visits",
            field=models.IntegerField(
                default=0, help_text="Visits from job boards/career sites"
            ),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="learning_hours_logged",
            field=models.FloatField(
                default=0.0, help_text="Hours spent learning/coding this day"
            ),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="milestones_achieved",
            field=models.IntegerField(
                default=0, help_text="Learning milestones reached this day"
            ),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="projects_worked_on",
            field=models.IntegerField(
                default=0, help_text="Number of projects/systems worked on"
            ),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="resume_downloads",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolioanalytics",
            name="skills_practiced",
            field=models.IntegerField(
                default=0, help_text="Number of skills actively practiced"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(help_text="Degree or course name", max_length=100),
        ),
        migrations.CreateModel(
            name="EducationSkillDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency_before",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=0,
                        help_text="Skill level before this course (0-5)",
                    ),
                ),
                (
                    "proficiency_after",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=1,
                        help_text="Skill level after this course (1-5)",
                    ),
                ),
                (
                    "learning_focus",
                    models.CharField(
                        choices=[
                            ("introduction", "First Introduction"),
                            ("foundation", "Foundation Building"),
                            ("practical", "Practical Application"),
                            ("advanced", "Advanced Concepts"),
                            ("mastery", "Mastery Level"),
                        ],
                        default="foundation",
                        help_text="Type of learning focus for this skill",
                        max_length=20,
                    ),
                ),
                (
                    "importance_level",
                    models.IntegerField(
                        choices=[
                            (1, "Minor Topic"),
                            (2, "Supporting Skill"),
                            (3, "Core Curriculum"),
                            (4, "Primary Focus"),
                        ],
                        default=3,
                        help_text="How central was this skill to the course",
                    ),
                ),
                (
                    "learning_notes",
                    models.TextField(
                        blank=True, help_text="Specific learning outcomes or notes"
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.education"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.skill"
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Skill Development",
                "unique_together": {("education", "skill")},
            },
        ),
        migrations.AddField(
            model_name="education",
            name="skills_learned",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills developed through this education",
                related_name="learned_through_education",
                through="core.EducationSkillDevelopment",
                to="core.skill",
            ),
        ),
    ]
