# Generated by Django 5.2.1 on 2025-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_education_career_relevance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("language", "Programming Language"),
                    ("framework", "Framework/Library"),
                    ("tool", "Development Tool"),
                    ("database", "Database"),
                    ("soft_skill", "Soft Skill"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
