# Generated by Django 5.2.1 on 2025-06-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_skill_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="certification_url",
            new_name="certificate_url",
        ),
    ]
