# Generated by Django 5.2.1 on 2025-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_certification_url_education_certificate_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
