# Generated by Django 5.2.1 on 2025-06-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_experience_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("language", "Programming Language"),
                    ("framework", "Framework/Library"),
                    ("tool", "Development Tool"),
                    ("database", "Database"),
                    ("soft_skill", "Soft Skill"),
                    ("api", "API Design/Development"),
                    ("data", "Data Engineering"),
                    ("system", "System Design/Development"),
                    ("ml", "Machine Learning"),
                    ("ui", "UX/UI & Design"),
                    ("ai", "AI"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
