# Generated by Django 5.2.1 on 2025-08-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_skill_category"),
        ("projects", "0013_systemskillgain_technologies_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical_concept", "Technical Concept"),
                    ("methodology", "Methodology/Process"),
                    ("soft_skill", "Soft Skill"),
                    ("domain_knowledge", "Domain Knowledge"),
                    ("other", "Other"),
                ],
                default="technical_concept",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SkillTechnologyRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        choices=[
                            (1, "Occasionally Used"),
                            (2, "Commonly Used"),
                            (3, "Essential Technology"),
                            (4, "Primary Implementation"),
                        ],
                        default=2,
                        help_text="How essential is this technology for this skill?",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("implementation", "Primary Implementation Tool"),
                            ("supporting", "Supporting Technology"),
                            ("alternative", "Alternative Implementation"),
                            ("data_source", "Data Source/Storage"),
                            ("visualization", "Visualization/Display"),
                            ("deployment", "Deployment/Infrastructure"),
                        ],
                        default="implementation",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Context about how this technology relates to the skill",
                    ),
                ),
                ("first_used_together", models.DateField(blank=True, null=True)),
                ("last_used_together", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technology_relations",
                        to="core.skill",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_relations",
                        to="projects.technology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill-Technology Relation",
                "verbose_name_plural": "Skill-Technology Relations",
                "unique_together": {("skill", "technology")},
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="related_technologies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Technologies commonly used with this skill",
                related_name="related_skills",
                through="core.SkillTechnologyRelation",
                to="projects.technology",
            ),
        ),
    ]
