# Generated by Django 5.2.1 on 2025-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_skill_category_skilltechnologyrelation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="category",
            field=models.CharField(
                choices=[
                    ("professional", "Professional & Coding-Centric"),
                    ("community", "Discussion & Community"),
                    ("media", "Media & Video"),
                    ("chat", "Messaging & Chat"),
                    ("blog", "Blogging & Content"),
                    ("other", "Other Socials"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
