# Generated by Django 5.2.1 on 2025-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sociallink_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="color",
            field=models.CharField(
                default="#60a5fa",
                help_text="Hex color for icon display (e.g., #00f0ff)",
                max_length=7,
            ),
        ),
    ]
