# Generated by Django 5.2.1 on 2025-09-15 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_sociallink_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                ],
                default=1,
                help_text="Skill level from 1-5",
            ),
        ),
    ]
