# Generated by Django 5.2.1 on 2025-10-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_skill_created_at_skill_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical_concept", "Technical Concepts"),
                    ("methodology", "Methodologies & Processes"),
                    ("soft_skill", "Soft Skills"),
                    ("domain_knowledge", "Domain Knowledge"),
                    ("other", "Other"),
                ],
                default="technical_concept",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="category",
            field=models.CharField(
                choices=[
                    ("professional", "Professional & Coding-Centric"),
                    ("community", "Discussion & Community"),
                    ("chat", "Messaging & Chat"),
                    ("blog", "Blogging & Content"),
                    ("media", "Media & Video"),
                    ("other", "Other Socials"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
