# Generated by Django 5.2.1 on 2025-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_skill_category_alter_sociallink_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="career_relevance",
        ),
        migrations.RemoveField(
            model_name="education",
            name="learning_intensity",
        ),
        migrations.RemoveField(
            model_name="education",
            name="platform",
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(
                help_text="Computer Science, Web Development, etc.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(
                help_text="e.g., 'edX HarvardX', 'Udemy', 'University of Alabama'",
                max_length=100,
            ),
        ),
    ]
