# Generated by Django 5.2.1 on 2025-10-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_education_career_relevance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="related_technology",
        ),
    ]
