# Generated by Django 5.2.1 on 2025-10-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_skill_related_technology"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceSkillApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_level",
                    models.IntegerField(
                        choices=[
                            (1, "Occasional Use"),
                            (2, "Regular Use"),
                            (3, "Core Responsibility"),
                        ],
                        default=2,
                        help_text="How central was this skill to this role?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_applications",
                        to="core.experience",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_applications",
                        to="core.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience Skill Application",
                "verbose_name_plural": "Experience Skill Applications",
                "ordering": ["-application_level", "skill__name"],
                "unique_together": {("experience", "skill")},
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="skills_applied",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills applied in this professional role",
                related_name="professional_experience",
                through="core.ExperienceSkillApplication",
                to="core.skill",
            ),
        ),
    ]
