# Generated by Django 5.2.1 on 2025-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_series_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_code_format",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("terminal", "Terminal"),
                    ("markdown", "Markdown"),
                    ("json", "JSON"),
                    ("sql", "SQL"),
                    ("bash", "Bash/Shell"),
                    ("plaintext", "Plain Text"),
                ],
                default="python",
                help_text="Programming language for syntac highlighting",
                max_length=20,
            ),
        ),
    ]
