# Generated by Django 5.2.1 on 2025-05-22 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_featured_code_format"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("development", "Development Log"),
                            ("documentation", "Technical Documentation"),
                            ("analysis", "System Analysis"),
                            ("update", "System Update"),
                            ("troubleshooting", "Troubleshooting"),
                            ("review", "System Review"),
                            ("enhancement", "Enhancement Log"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Normal"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "log_entry_id",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated log entry ID",
                        max_length=20,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_number",
                    models.CharField(
                        blank=True,
                        help_text="System version this log relates to",
                        max_length=20,
                    ),
                ),
                (
                    "completion_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="How much this log entry contributed to project completion (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_connections",
                        to="blog.post",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="projects.systemmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "unique_together": {("post", "system")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="related_systems",
            field=models.ManyToManyField(
                blank=True,
                help_text="Systems this log entry relates to",
                related_name="related_posts",
                through="blog.SystemLogEntry",
                to="projects.systemmodule",
            ),
        ),
    ]
