# Generated by Django 5.2.1 on 2025-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_systemlogentry_post_related_systems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemlogentry",
            options={
                "ordering": ["-logged_at"],
                "verbose_name": "System Log Entry",
                "verbose_name_plural": "System Log Entries",
            },
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="version_number",
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="affected_components",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of affected system components",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="log_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="performance_impact",
            field=models.CharField(
                choices=[
                    ("positive", "Positive Impact"),
                    ("negative", "Negative Impact"),
                    ("neutral", "No Impact"),
                    ("unknown", "Unknown"),
                ],
                default="neutral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this log entry was resolved/completed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="system_version",
            field=models.CharField(
                blank=True,
                help_text="System version this log relates to (e.g. v1.2.3)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemlogentry",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("development", "Development Log"),
                    ("documentation", "Technical Documentation"),
                    ("analysis", "System Analysis"),
                    ("update", "System Update"),
                    ("troubleshooting", "Troubleshooting"),
                    ("review", "System Review"),
                    ("enhancement", "Feature Enhancement"),
                    ("deployment", "Deployment Log"),
                    ("testing", "Testing Results"),
                    ("performance", "Performance Analysis"),
                    ("security", "Security Assessment"),
                    ("integration", "Integration Notes"),
                ],
                default="development",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemlogentry",
            name="log_entry_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated log entry ID (e.g. SYS-001-LOG-042)",
                max_length=20,
            ),
        ),
    ]
