# Generated by Django 5.2.1 on 2025-06-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_systemlogentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="systemlogentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "System Log Entry",
                "verbose_name_plural": "System Log Entries",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="systemlogentry",
            old_name="logged_at",
            new_name="created_at",
        ),
    ]
