# Generated by Django 5.2.1 on 2025-06-11 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_options_alter_systemlogentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="series",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="intermediate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="is_complete",
            field=models.BooleanField(
                default=False, help_text="Is this series complete or ongoing?"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Feature this series prominently"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="post_count",
            field=models.IntegerField(
                default=0, help_text="Number of posts in series (auto-calculated)"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Series thumbnail image (400x300px recommended)",
                null=True,
                upload_to="blog/series/",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="total_reading_time",
            field=models.IntegerField(
                default=0,
                help_text="Total reading time for all posts in series (auto-calculated)",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
