# Generated by Django 5.2.1 on 2025-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_series_created_at_series_difficulty_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlogentry",
            name="actual_hours",
            field=models.IntegerField(
                blank=True, help_text="Actual hours spent on this work", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="estimated_hours",
            field=models.IntegerField(
                blank=True, help_text="Estimated hours to complete this work", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="impact_level",
            field=models.CharField(
                choices=[
                    ("low", "Low Impact"),
                    ("medium", "Medium Impact"),
                    ("high", "High Impact"),
                    ("critical", "Critical Impact"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="resolution_notes",
            field=models.TextField(
                blank=True, help_text="Notes on how this issue was resolved"
            ),
        ),
    ]
