# Generated by Django 5.2.1 on 2025-10-06 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_systemlogentry_actual_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Subscriber's email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the subscription is active"
                    ),
                ),
                (
                    "subscribed_to_all",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications for all new posts",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for email verification",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether email has been verified"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "subscribed_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific categories to subscribe to",
                        related_name="subscribers",
                        to="blog.category",
                    ),
                ),
                (
                    "subscribed_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific tags to subscribe to",
                        related_name="subscribers",
                        to="blog.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
