# Generated by Django 5.2.1 on 2025-10-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="subscribed_to_all",
            field=models.BooleanField(
                default=False, help_text="Receive notifications for all new posts"
            ),
        ),
    ]
