# Generated by Django 5.2.1 on 2025-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemlogentry",
            name="actual_hours",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="affected_components",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="completion_impact",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="estimated_hours",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="impact_level",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="log_status",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="performance_impact",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="resolution_notes",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="resolved_at",
        ),
        migrations.RemoveField(
            model_name="systemlogentry",
            name="system_version",
        ),
        migrations.AddField(
            model_name="systemlogentry",
            name="relationship_priority",
            field=models.IntegerField(
                choices=[(1, "Mentioned"), (2, "Related"), (3, "Primary")], default=2
            ),
        ),
    ]
