# Generated by Django 5.2.1 on 2025-05-13 19:18

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Series",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_date"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="published",
            new_name="published_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="featured_image",
        ),
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(
                default="QT",
                help_text="Two-letter code for display in hexagon",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#00f0ff",
                help_text="Hex color code (e.g., #00f0ff)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon name (e.g., fa-book-open)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Large banner img for post header (1200x400px recommended)",
                null=True,
                upload_to="blog/banners/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Feature this post on the blog homepage"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_code",
            field=models.TextField(
                blank=True, help_text="Code snippet to display in featured section"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="show_toc",
            field=models.BooleanField(
                default=True, help_text="Show table of contents on post page"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Small image for post cards (300x200px recommended)",
                null=True,
                upload_to="blog/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Short description for display in post cards"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=0, editable=False, help_text="Estimated reading time in minutes"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("viewed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_on"],
                "unique_together": {("post", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="SeriesPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_associations",
                        to="blog.post",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blog.series",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("series", "post")},
            },
        ),
    ]
